# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# We dont want that hint for syntax constructors in a few cases, no cases otherwise
- ignore: {name: "Avoid lambda using `infix`"}
